/* Generated by npm run sync-supabase-config — do not commit real keys to a public repo */
window.AETHER_CONFIG = {
  supabaseUrl: "https://qddlhzhgcquamwuwggnw.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkZGxoemhnY3F1YW13dXdnZ253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NDkxNTIsImV4cCI6MjA5MDUyNTE1Mn0.vahSNfcFe2LMq2tjvziQLupqOo3fdZG9_1-AkRw06iE",
};
