/* Generated by npm run sync-supabase-config — do not commit real keys to a public repo */
window.AETHER_CONFIG = {
  supabaseUrl: "https://qddlhzhgcquamwuwggnw.supabase.co",
  supabaseAnonKey: "sb_publishable_1GcjOp73BV2K-xfH1aaCxg_cASvn5s6",
};
